on: push

name: Test

jobs:
  run-check:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !contains(github.event.head_commit.message, '[ci skip]')
    steps:
      - run: echo "Run"

  lint:
    needs: run-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-detekt
        with:
          detekt-version: v1.15.0
      - run: ./gradlew assemble
      - run: detekt --plugins build/libs/detekt-kdoc-ruleset-*.jar --config detect-confg.yml

  test:
    needs: run-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 15
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - run: ./gradlew test
